version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: npm run start
    volumes:
      - "./src:/usr/src/app/src"
      - "./data:/usr/src/app/data"
    container_name: disc-bot
